import './globals.css'
import { Raleway } from 'next/font/google'
import { MainNav } from '@/components/main_nav';
import { routeConfig } from '@/config/route';

const raleway = Raleway({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <MainNav 
          items={routeConfig.mainNav} 
        />
        <div className='pt-[5rem] bg-background'>
          {children}
        </div>
      </body>
    </html>
  )
}
